query Page($slug: String!, $stage: Stage! = PUBLISHED) {
  page(where: { slug: $slug }, stage: $stage) {
    __typename
    id
    slug
    title
    description
    ogImage {
      url
    }
    components {
      ... on Editorial {
        id
        __typename
        image {
          url(
            transformation: {
              document: { output: { format: webp } }
              image: { resize: { width: 1000, height: 1504, fit: max } }
            }
          )
        }
        components {
          ... on Card {
            id
            __typename
            cta
            image {
              url(
                transformation: {
                  image: { resize: { height: 500, width: 500 } }
                  document: { output: { format: webp } }
                }
              )
            }
            title
            url
          }
          ... on Cta {
            id
            __typename
            chapeau
            cta
            description
            title
            url
          }
        }
      }
      ... on Hero {
        id
        __typename
        description
        image {
          url(
            transformation: {
              document: { output: { format: webp } }
              image: { resize: { width: 2880, height: 1264, fit: max } }
            }
          )
        }
        title
      }
      ... on ProductHighlight {
        id
        __typename
        productFocus {
          id
          __typename
          cta
          description
          image {
            url(
              transformation: {
                document: { output: { format: webp } }
                image: { resize: { width: 2880, height: 1264, fit: max } }
              }
            )
          }
          productId
          title
          url
          product {
            description
            id
            images {
              alt
              url
            }
            ingredients
            price
            name
            shortDescription
            slug
            stock
          }
        }
      }
      ... on Routine {
        id
        __typename
        chapeau
        cta
        description
        image {
          url(
            transformation: {
              document: { output: { format: webp } }
              image: { resize: { width: 768, height: 510, fit: max } }
            }
          )
        }
        title
        url
      }
    }
  }
}
