query Pdp($slug: String!, $stage: Stage! = PUBLISHED) {
  pdp(where: { slug: $slug }, stage: $stage) {
    id
    __typename
    slug
    title
    description
    ogImage {
      url
    }
    components {
      ... on Tutorial {
        __typename
        id
        title
        image {
          url(
            transformation: {
              document: { output: { format: webp } }
              image: { resize: { width: 2880, height: 1264, fit: max } }
            }
          )
        }
        items {
          __typename
          text
        }
      }
      ... on Routine {
        __typename
        id
        chapeau
        cta
        description
        image {
          url(
            transformation: {
              document: { output: { format: webp } }
              image: { resize: { width: 768, height: 510, fit: max } }
            }
          )
        }
        title
        url
      }
      ... on ProductList {
        __typename
        title
        relatedProductList {
          relatedProductId
          relatedProducts {
            products {
              description
              id
              images {
                alt
                url
              }
              ingredients
              name
              price
              shortDescription
              slug
              stock
            }
          }
        }
      }
    }

    product {
      id
      slug
      name
      price
      ingredients
      shortDescription
      description
      stock
      images {
        alt
        url
      }
    }
  }
}
